import { readFileSync } from 'node:fs'
import * as icons from 'lucide-react'
import { describe, expect, it } from 'vitest'
import type { PluginRecord } from '../../shared/plugins'
import type { SidebarViewId } from '../../shared/types'
import { buildNavigationDefinitions, type NavigationEntry } from './navigationDefinitions'
import { emptySidebarLayout, parseSidebarLayout, resolveSidebarGroups, type SidebarGroup } from './sidebarLayout'

type NavigationInput = Parameters<typeof buildNavigationDefinitions>[0]
interface BaselineGroup {
  groupKey: string
  label: string
  items: Array<[SidebarViewId, string, keyof typeof icons]>
}
interface BaselineScenario {
  name: string
  project: string
  uiMode: NavigationInput['uiMode']
  plugins: string
  contentFeatures: NavigationInput['contentFeatures']
  groups: number[]
  labelMap: number
  navOrderStorageKey: string
  sidebarLayoutStorageKey: string
}

// Captured by evaluating App.tsx at this checkpoint, before extracting its logic.
// Expected values are fixtures, never generated by buildNavigationDefinitions.
const baseline = JSON.parse(readFileSync(new URL('./__fixtures__/extensionDefinitions.baseline.json', import.meta.url), 'utf8')) as {
  sourceCommit: string
  projects: Record<string, NavigationInput['project']>
  plugins: Record<string, PluginRecord[]>
  groups: BaselineGroup[]
  labelMaps: Array<Partial<Record<SidebarViewId, string>>>
  scenarios: BaselineScenario[]
}

const inputFor = (scenario: BaselineScenario): NavigationInput => ({
  project: baseline.projects[scenario.project],
  uiMode: scenario.uiMode,
  plugins: baseline.plugins[scenario.plugins],
  contentFeatures: scenario.contentFeatures
})
const groupFromBaseline = (index: number): SidebarGroup<NavigationEntry> => {
  const group = baseline.groups[index]
  return { ...group, items: group.items.map(([id, label, icon]) => ({ id, label, icon: icons[icon] as icons.LucideIcon })) }
}
const groupIds = (groups: SidebarGroup[]) => groups.map(group => [group.groupKey, group.label, group.items.map(item => item.id)])

describe('navigation compatibility with the pre-extraction checkpoint', () => {
  it.each(baseline.scenarios)('$name', scenario => {
    const actual = buildNavigationDefinitions(inputFor(scenario))
    expect(actual.baseVisibleNavGroups).toEqual(scenario.groups.map(groupFromBaseline))
    expect(actual.navLabelMap).toEqual(baseline.labelMaps[scenario.labelMap])
    expect(actual.navOrderStorageKey).toBe(scenario.navOrderStorageKey)
    expect(actual.sidebarLayoutStorageKey).toBe(scenario.sidebarLayoutStorageKey)
  })

  it('retains custom groups, unavailable entries, hidden preferences and old numeric group keys', () => {
    const definitions = buildNavigationDefinitions({
      project: baseline.projects.modpack, uiMode: 'beginner',
      plugins: baseline.plugins.panel, contentFeatures: { ftbQuests: true, patchouli: true }
    })
    const layout = parseSidebarLayout({
      ...emptySidebarLayout(),
      customGroups: [{ groupKey: 'custom-tools', label: '常用' }],
      deletedGroups: ['1'],
      hiddenItems: ['plugin:panel-a', 'patchouli'],
      labels: { 0: '创作空间' },
      orders: { 'custom-tools': ['plugin:panel-a', 'patchouli', 'plugin:absent'], 0: ['modpack-server', 'workspace'] },
      groupOrder: ['custom-tools', '2', '0']
    })
    const storedLayout = JSON.stringify(layout)
    expect(groupIds(resolveSidebarGroups(definitions.baseVisibleNavGroups, layout))).toEqual([
      ['custom-tools', '常用', ['plugin:panel-a', 'patchouli']],
      ['2', '插件', ['plugin:panel-z', 'plugins']],
      ['0', '创作空间', ['modpack-server', 'workspace', 'inspiration', 'ftb-quests', 'code', 'minecraft']],
      ['ungrouped', '未分类', ['modpack-resourcepacks']]
    ])
    expect(JSON.stringify(layout)).toBe(storedLayout)

    const withoutOptionalEntries = buildNavigationDefinitions({
      project: baseline.projects.modpack, uiMode: 'beginner', plugins: [],
      contentFeatures: { ftbQuests: false, patchouli: false }
    })
    expect(resolveSidebarGroups(withoutOptionalEntries.baseVisibleNavGroups, layout).find(group => group.groupKey === 'custom-tools')?.items).toEqual([])
    expect(JSON.stringify(layout)).toBe(storedLayout)
    expect(resolveSidebarGroups(definitions.baseVisibleNavGroups, layout).find(group => group.groupKey === 'custom-tools')?.items.map(item => item.id)).toEqual(['plugin:panel-a', 'patchouli'])
  })

  it('does not share mutable navigation entries between builds or mutate plugin snapshots', () => {
    const input = inputFor(baseline.scenarios.find(scenario => scenario.project === 'modpack' && scenario.plugins === 'panel')!)
    const snapshot = JSON.stringify(input)
    const first = buildNavigationDefinitions(input)
    const second = buildNavigationDefinitions(input)
    first.baseVisibleNavGroups[0].items[0].label = 'Changed by consumer'
    first.baseVisibleNavGroups[0].items.pop()
    expect(buildNavigationDefinitions(input)).toEqual(second)
    expect(JSON.stringify(input)).toBe(snapshot)
  })
})
