import { useEffect, useRef, useState, type ReactNode } from 'react'
import { CheckCheck, Download, FilePlus2, FolderOpen, Image, LoaderCircle, Paintbrush, Play, Plus, RefreshCw, Save, Trash2, Upload, X } from 'lucide-react'
import type { ProjectInfo } from '../../../shared/types'
import { suggestedResourcePackFormat, type ResourcePackInfo, type ResourcePackValidation } from '../../../shared/resourcePack'
import MonacoCodeEditor from './MonacoCodeEditor'
import MiniPaintEditor from './MiniPaintEditor'
import { useConfirmDialog, usePromptDialog } from './InteractionDialogs'
import '../resource-packs.css'

export default function ResourcePackWorkspace({ project, darkMode, onImages, onModels, onTest, installed }: { project: ProjectInfo; darkMode: boolean; onImages: () => void; onModels: () => void; onTest: () => void; installed?: ReactNode }): React.JSX.Element {
  const [tab, setTab] = useState<'author' | 'installed'>('author')
  const [packs, setPacks] = useState<ResourcePackInfo[]>([])
  const [id, setId] = useState('')
  const [file, setFile] = useState('')
  const [text, setText] = useState('')
  const [savedText, setSavedText] = useState('')
  const [image, setImage] = useState('')
  const [baseline, setBaseline] = useState('')
  const [painting, setPainting] = useState(false)
  const [busy, setBusy] = useState(false)
  const [notice, setNotice] = useState('')
  const [validation, setValidation] = useState<ResourcePackValidation | null>(null)
  const [creating, setCreating] = useState(false)
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [format, setFormat] = useState<number | ''>(suggestedResourcePackFormat(project.minecraftVersion) ?? '')
  const [query, setQuery] = useState('')
  const loadToken = useRef(0)
  const { confirm, dialog } = useConfirmDialog()
  const { prompt, dialog: promptDialog } = usePromptDialog()
  const pack = packs.find(item => item.id === id)
  const dirty = text !== savedText
  const refresh = async (select?: string): Promise<void> => { const items = await window.modmind.resourcePacks.list(project.path); setPacks(items); if (select) setId(select); else setId(previous => items.some(item => item.id === previous) ? previous : items[0]?.id ?? '') }
  useEffect(() => { let active = true; void window.modmind.resourcePacks.list(project.path).then(items => { if (active) { setPacks(items); setId(items[0]?.id ?? '') } }).catch(error => { if (active) setNotice(String(error)) }); return () => { active = false; loadToken.current++ } }, [project.path])
  const run = async (action: () => Promise<void>): Promise<void> => { if (busy) return; setBusy(true); setNotice(''); try { await action() } catch (error) { setNotice(error instanceof Error ? error.message : String(error)) } finally { setBusy(false) } }
  const canLeave = (): Promise<boolean> => dirty || painting ? confirm({ title: '离开当前编辑', message: '尚未保存的修改将丢失。', confirmLabel: '离开', tone: 'danger' }) : Promise.resolve(true)
  const openFile = async (next: string): Promise<void> => {
    if (!await canLeave()) return
    const token = ++loadToken.current
    setPainting(false)
    await run(async () => { const value = await window.modmind.resourcePacks.read(project.path, id, next); if (token !== loadToken.current) return; setFile(next); setText(value.text ?? ''); setSavedText(value.text ?? ''); setImage(value.dataUrl ?? ''); setBaseline(value.baseline) })
  }
  const save = async (content = text): Promise<void> => {
    const next = await window.modmind.resourcePacks.write(project.path, id, file, content, baseline)
    setPacks(previous => previous.map(item => item.id === next.id ? next : item))
    const value = await window.modmind.resourcePacks.read(project.path, id, file)
    setBaseline(value.baseline); setText(value.text ?? ''); setSavedText(value.text ?? ''); setImage(value.dataUrl ?? ''); setValidation(null); setNotice('已保存')
  }
  const selectPack = async (next: string): Promise<void> => { if (await canLeave()) { loadToken.current++; setId(next); setFile(''); setText(''); setSavedText(''); setImage(''); setPainting(false); setValidation(null) } }
  if (tab === 'installed' && installed) return <div className="resource-pack-workspace"><div className="resource-pack-toolbar"><button className="secondary-button" onClick={() => setTab('author')}>制作资源包</button><strong>整合包内资源包 <em className="agent-beta-tag">Beta</em></strong></div>{installed}</div>
  return <div className="resource-pack-workspace">{installed ? <div className="resource-pack-toolbar"><strong>制作资源包</strong><button className="secondary-button" onClick={() => void (async () => { if (await canLeave()) setTab('installed') })()}>整合包内资源包</button></div> : null}<header className="content-toolbar"><div><h1>资源包 <em className="agent-beta-tag">Beta</em></h1><p>{project.name} · {project.minecraftVersion}</p></div><div className="resource-pack-actions"><button className="icon-button" title="刷新资源包" disabled={busy} onClick={() => void run(() => refresh())}><RefreshCw size={16} /></button><button className="secondary-button" disabled={busy} onClick={() => setCreating(true)}><Plus size={15} />新建</button><button className="secondary-button" disabled={busy} onClick={() => void run(async () => { const value = await window.modmind.resourcePacks.import(project.path); if (value) await refresh(value.id) })}><Upload size={15} />导入 ZIP</button><button className="icon-button" title="导入资源包目录" disabled={busy} onClick={() => void run(async () => { const value = await window.modmind.resourcePacks.import(project.path, true); if (value) await refresh(value.id) })}><FolderOpen size={17} /></button></div></header>
    <div className="resource-pack-toolbar"><label>当前资源包<select value={id} disabled={busy} onChange={event => void selectPack(event.target.value)}><option value="" disabled>选择资源包</option>{packs.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><span>{pack?.files.length ?? 0} 个文件</span><div className="resource-pack-actions"><button className="icon-button" title="图像工坊" onClick={onImages}><Paintbrush size={16} /></button><button className="secondary-button" onClick={onModels}>模型</button><button className="secondary-button" disabled={busy || !pack} onClick={() => void run(async () => { setValidation(await window.modmind.resourcePacks.validate(project.path, id)) })}><CheckCheck size={15} />校验</button><button className="secondary-button" disabled={busy || !pack || dirty} onClick={() => void run(async () => { const result = await window.modmind.resourcePacks.deploy(project.path, id); setNotice(`${result.message}：${result.path}`) })}><Play size={15} />部署测试</button><button className="primary-button" disabled={busy || !pack || dirty} onClick={() => void run(async () => { const target = await window.modmind.resourcePacks.export(project.path, id); if (target) setNotice(`已导出：${target}`) })}><Download size={15} />导出 ZIP</button></div></div>
    <div className="resource-pack-body"><aside className="resource-pack-files"><div className="resource-pack-file-tools"><input aria-label="筛选资源文件" value={query} onChange={event => setQuery(event.target.value)} placeholder="筛选文件" /><button className="icon-button" title="新建资源文件" disabled={!pack || busy} onClick={() => void (async () => { const next = await prompt({ title: '新建资源文件', inputLabel: '包内相对路径', value: `assets/${project.namespace}/lang/zh_cn.json` }); if (!next) return; await run(async () => { await window.modmind.resourcePacks.write(project.path, id, next, next.endsWith('.json') ? '{}\n' : '', null); await refresh() }) })()}><FilePlus2 size={16} /></button><button className="icon-button" title="导入素材" disabled={!pack || busy} onClick={() => void (async () => { const directory = await prompt({ title: '导入素材', inputLabel: '目标目录', value: `assets/${project.namespace}/textures/item` }); if (directory) await run(async () => { await window.modmind.resourcePacks.importAssets(project.path, id, directory); await refresh() }) })()}><Upload size={16} /></button></div>{pack?.files.filter(item => item.path.toLowerCase().includes(query.toLowerCase())).map(item => <button key={item.path} className={`resource-pack-file${file === item.path ? ' active' : ''}`} disabled={busy} title={item.path} onClick={() => void openFile(item.path)}>{item.kind === 'image' ? <Image size={14} /> : <FilePlus2 size={14} />}<span>{item.path}</span></button>)}</aside>
      <section className="resource-pack-editor"><div className="resource-pack-editor-heading"><span>{file || pack?.description || '选择资源文件'}</span>{file ? <div className="resource-pack-actions">{image.startsWith('data:image/') ? <button className="secondary-button" onClick={() => setPainting(value => !value)}><Paintbrush size={15} />{painting ? '预览' : '编辑图像'}</button> : null}<button className="icon-button" title="删除文件" disabled={busy || file === 'pack.mcmeta'} onClick={() => void (async () => { if (await confirm({ title: '删除资源文件', message: file, confirmLabel: '删除', tone: 'danger' })) await run(async () => { await window.modmind.resourcePacks.removeFile(project.path, id, file, baseline); setFile(''); setImage(''); setText(''); setSavedText(''); await refresh() }) })()}><Trash2 size={15} /></button>{!image ? <button className="icon-button" title="保存文件" disabled={busy || !dirty} onClick={() => void run(() => save())}><Save size={16} /></button> : null}</div> : null}</div>
      {painting && image.startsWith('data:image/') ? <MiniPaintEditor key={`${id}:${file}`} asset={{ id: `${id}:${file}`, dataUrl: image, createdAt: '', model: 'resource-pack', style: 'minecraft', size: '', quality: 'auto', hosted: false, credits: 0 }} darkMode={darkMode} onError={setNotice} onSave={value => save(value)} /> : image.startsWith('data:image/') ? <div className="resource-pack-image"><img src={image} alt={file} /></div> : image.startsWith('data:audio/') ? <audio controls src={image} /> : file ? <MonacoCodeEditor path={`${project.path}/resource-packs/${id}/${file}`} language={file.endsWith('.json') || file.endsWith('.mcmeta') ? 'json' : 'plaintext'} value={text} darkMode={darkMode} onChange={setText} onSave={() => void run(() => save())} /> : <div className="resource-pack-empty"><FolderOpen size={28} /><p>{pack ? '选择文件' : '暂无资源包'}</p><button className="secondary-button" onClick={onTest}><Play size={15} />游戏测试</button></div>}</section></div>
    {validation ? <section className="resource-pack-validation"><strong>{validation.success ? '结构校验通过' : '校验未通过'} · {validation.checked} 个文件</strong>{validation.issues.map((issue, index) => <button key={index} onClick={() => void openFile(issue.path)}><span>{issue.severity === 'error' ? '错误' : '提示'}</span> {issue.path}：{issue.message}</button>)}<small>实际显示效果需要在客户端加载后验证</small></section> : null}
    {notice || busy ? <div className="resource-pack-notice" role="status">{busy ? <LoaderCircle className="spin" size={15} /> : null}{notice || '处理中…'}</div> : null}
    {creating ? <div className="modal-backdrop"><form className="dialog" role="dialog" aria-modal="true" aria-label="新建资源包" onSubmit={event => { event.preventDefault(); void run(async () => { const value = await window.modmind.resourcePacks.create(project.path, { name, description, packFormat: Number(format) }); setCreating(false); await refresh(value.id) }) }}><div className="dialog-header"><h2>新建资源包</h2><button className="icon-button" title="关闭" type="button" onClick={() => setCreating(false)}><X size={16} /></button></div><label className="field-label">名称<input required value={name} maxLength={80} onChange={event => setName(event.target.value)} /></label><label className="field-label">描述<input value={description} maxLength={4000} onChange={event => setDescription(event.target.value)} /></label><label className="field-label">资源包格式版本<input required type="number" min={1} max={10000} value={format} onChange={event => setFormat(event.target.value ? Number(event.target.value) : '')} /></label><div className="dialog-footer"><button className="primary-button" disabled={busy || !name.trim() || !format}><Plus size={15} />创建</button></div></form></div> : null}{dialog}{promptDialog}
  </div>
}
