import type { ManagedItem } from '../shared/itemEditor'
import type { ProjectInfo } from '../shared/types'
import { compareMinecraftVersions } from './loaderCompatibility'

export const itemEditorMarker = '// Generated by ModMind item editor. Edit items in the app.'

export function itemEditorSupportReason(project: ProjectInfo): string | undefined {
  if (project.kind === 'modpack' || project.kind === 'server-plugin' || !['fabric', 'quilt', 'forge', 'neoforge'].includes(project.loader)) return '物品与装备编辑器仅适用于 Java 自制 Mod。'
  if (project.draft) return '请先初始化项目。'
  if (!/^[a-z][a-z0-9_]*$/.test(project.namespace)) return '项目命名空间不符合 Java 包名要求。'
  const version = project.minecraftVersion
  const supported = project.loader === 'fabric' ? ['1.20.1', '1.21.1'].includes(version)
    : project.loader === 'quilt' ? ['1.20.1', '1.21'].includes(version)
      : project.loader === 'forge' ? ['1.20.1', '1.21.1'].includes(version)
        : version === '1.21.1'
  if (!supported) return `当前生成器尚未验证 ${project.loader} / Minecraft ${version}。`
  return undefined
}

export function itemEditorPaths(project: ProjectInfo): { java: string; descriptor: string | null; assets: string } {
  return {
    java: `src/main/java/dev/modmind/${project.namespace}/generated/ModMindItems.java`,
    descriptor: project.loader === 'fabric' ? 'src/main/resources/fabric.mod.json'
      : project.loader === 'quilt' ? 'src/main/resources/quilt.mod.json' : null,
    assets: `src/main/resources/assets/${project.namespace}`
  }
}

function itemProperties(item: ManagedItem, modern: boolean): string {
  let value = `new Item.Properties().stacksTo(${item.stackSize})`
  if (item.durability) value += `.durability(${item.durability})`
  const tier = `Tiers.${(item.tier ?? 'iron').toUpperCase()}`
  if (modern && item.kind === 'sword') value += `.attributes(SwordItem.createAttributes(${tier}, ${item.attackDamage ?? 3}, ${item.attackSpeed ?? -2.4}F))`
  else if (modern && ['pickaxe', 'axe', 'shovel', 'hoe'].includes(item.kind)) value += `.attributes(DiggerItem.createAttributes(${tier}, ${item.attackDamage ?? 1}F, ${item.attackSpeed ?? -2.8}F))`
  return value
}

function itemConstructor(item: ManagedItem, modern: boolean): string {
  const properties = itemProperties(item, modern)
  if (item.kind === 'item') return `new Item(${properties})`
  if (item.kind === 'armor') return `new ArmorItem(ArmorMaterials.${(item.armorMaterial ?? 'iron').toUpperCase()}, ArmorItem.Type.${(item.armorSlot ?? 'helmet').toUpperCase()}, ${properties})`
  const tier = `Tiers.${(item.tier ?? 'iron').toUpperCase()}`
  const type = ({ sword: 'SwordItem', pickaxe: 'PickaxeItem', axe: 'AxeItem', shovel: 'ShovelItem', hoe: 'HoeItem' } as Record<string, string>)[item.kind]
  if (modern) return `new ${type}(${tier}, ${properties})`
  const subclass = ['pickaxe', 'axe', 'hoe'].includes(item.kind) ? ' {}' : ''
  return `new ${type}(${tier}, ${item.attackDamage ?? 1}, ${item.attackSpeed ?? -2.8}F, ${properties})${subclass}`
}

export function generatedItemJava(project: ProjectInfo, items: ManagedItem[]): string {
  const modern = compareMinecraftVersions(project.minecraftVersion, '1.20.5') >= 0
  const location = modern ? 'ResourceLocation.fromNamespaceAndPath(MOD_ID, id)' : 'new ResourceLocation(MOD_ID, id)'
  const packageName = `dev.modmind.${project.namespace}.generated`
  const common = `package ${packageName};

import net.minecraft.world.item.*;
import net.minecraft.resources.ResourceLocation;
`
  const lines = items.map(item => `        register(${JSON.stringify(item.id)}, ${itemConstructor(item, modern)});`).join('\n')

  if (project.loader === 'fabric' || project.loader === 'quilt') {
    const quilt = project.loader === 'quilt'
    return `${itemEditorMarker}
${common}import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
${quilt ? 'import org.quiltmc.loader.api.ModContainer;\nimport org.quiltmc.qsl.base.api.entrypoint.ModInitializer;' : 'import net.fabricmc.api.ModInitializer;'}

public final class ModMindItems implements ModInitializer {
    private static final String MOD_ID = ${JSON.stringify(project.namespace)};

    @Override
    public void onInitialize(${quilt ? 'ModContainer mod' : ''}) {
${lines}
    }

    private static void register(String id, Item item) {
        Registry.register(BuiltInRegistries.ITEM, ${location}, item);
    }
}
`
  }

  if (project.loader === 'forge') {
    return `${itemEditorMarker}
${common}import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegisterEvent;

@Mod.EventBusSubscriber(modid = ${JSON.stringify(project.namespace)}, bus = Mod.EventBusSubscriber.Bus.MOD)
public final class ModMindItems {
    private static final String MOD_ID = ${JSON.stringify(project.namespace)};

    @SubscribeEvent
    public static void registerItems(RegisterEvent event) {
        event.register(ForgeRegistries.Keys.ITEMS, helper -> {
${items.map(item => `            helper.register(${location.replace('id', JSON.stringify(item.id))}, ${itemConstructor(item, modern)});`).join('\n')}
        });
    }
}
`
  }

  return `${itemEditorMarker}
${common}import net.minecraft.core.registries.Registries;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.registries.RegisterEvent;

@EventBusSubscriber(modid = ${JSON.stringify(project.namespace)}, bus = EventBusSubscriber.Bus.MOD)
public final class ModMindItems {
    private static final String MOD_ID = ${JSON.stringify(project.namespace)};

    @SubscribeEvent
    public static void registerItems(RegisterEvent event) {
        event.register(Registries.ITEM, helper -> {
${items.map(item => `            helper.register(${location.replace('id', JSON.stringify(item.id))}, ${itemConstructor(item, modern)});`).join('\n')}
        });
    }
}
`
}
