export const MODPACK_AGENT_WORKFLOW_GUIDANCE = `MODPACK WORKSPACE GUIDANCE:
- The current project may contain a modpack, an adopted instance, or self-authored modules. Inspect the files and use the layout that best matches the request.
- Delegate self-authored mod source tasks. Use modmind_modpack_modules list to identify the registered namespace, then modmind_modpack_delegate_module with the concrete requirements, acceptance criteria and relevant pack constraints. The module workbench runs its own agent with module-specific skills, source, dependencies and managed build/test tools. Do not implement module source yourself or load Java development skills into the pack coordinator. Linked module tasks change the original source project.
- Delegation returns a taskId immediately. Use modmind_modpack_module_task with waitSeconds:20 until it finishes; continue unrelated pack work while it runs, but do not edit/build that module concurrently. Read every task result before the final answer or pack build. Review the returned summary, changed files, verification and remaining work. A child answer is not proof of completion. Refine and delegate remaining module work when needed; do not silently claim partial or blocked work is done. Once module work is ready, call modmind_build_project to compile all pack modules and synchronize their current JARs into the pack test instance, then run relevant pack-level checks. No project switching or repeated user instructions are needed. Third-party JARs without registered source cannot receive source-development delegation.
- Match the request to the bundled modpack authoring, migration, server-pack testing, or release workflow. Use the workflow as an acceptance checklist, not as evidence by itself.
- Use modmind_modpack_plan followed by modmind_modpack_apply_plan for managed mod files, modmind_modpack_download_content for non-mod pack content, and the dedicated quest, guide, keybind, optimization, migration, and server tools when they cover the operation. Pass reviewed tool output forward instead of reconstructing it.
- Managed download paths are mandatory when available. Native tools remain available for uncovered work or after the matching managed operation returns an actual failure.
- Validate content and run the smallest relevant client, server, join, or scenario check before declaring the pack complete.
- Make the requested changes directly and explain any assumptions or verification results in the final response.`
