// Projective texture mapping: every UI pixel shares a single homography.
const surface=document.createElement('canvas');surface.width=1920;surface.height=1080;
const gl=surface.getContext('webgl',{alpha:true,premultipliedAlpha:false,preserveDrawingBuffer:true});
if(!gl)throw Error('视频渲染需要 WebGL');
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,'attribute vec2 pos;void main(){gl_Position=vec4(pos,0.,1.);}'));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,`precision highp float;uniform sampler2D img;uniform mat3 inverseH;uniform float dof;void main(){vec3 v=inverseH*vec3(gl_FragCoord.x,1080.-gl_FragCoord.y,1.);vec2 uv=v.xy/v.z;if(uv.x<0.||uv.y<0.||uv.x>1.||uv.y>1.)discard;vec2 px=vec2(1./1400.,1./876.);float r=dof*(.3+smoothstep(.32,.95,uv.x)*2.8);vec4 c=texture2D(img,uv)*.28;c+=texture2D(img,uv+px*vec2(r,0.))*.12;c+=texture2D(img,uv-px*vec2(r,0.))*.12;c+=texture2D(img,uv+px*vec2(0.,r))*.12;c+=texture2D(img,uv-px*vec2(0.,r))*.12;c+=texture2D(img,uv+px*vec2(r,r))*.06;c+=texture2D(img,uv-px*vec2(r,r))*.06;c+=texture2D(img,uv+px*vec2(r,-r))*.06;c+=texture2D(img,uv-px*vec2(r,-r))*.06;gl_FragColor=c;}`));gl.linkProgram(p);gl.useProgram(p);
const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);let a=gl.getAttribLocation(p,'pos');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,2,gl.FLOAT,false,0,0);const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);const loc=gl.getUniformLocation(p,'inverseH');
function solve(A,b){for(let i=0;i<b.length;i++){let m=i;for(let j=i+1;j<b.length;j++)if(Math.abs(A[j][i])>Math.abs(A[m][i]))m=j;[A[i],A[m]]=[A[m],A[i]];[b[i],b[m]]=[b[m],b[i]];let d=A[i][i];if(Math.abs(d)<1e-12)throw Error('退化的投影平面');for(let k=i;k<b.length;k++)A[i][k]/=d;b[i]/=d;for(let j=0;j<b.length;j++){if(i===j)continue;d=A[j][i];for(let k=i;k<b.length;k++)A[j][k]-=d*A[i][k];b[j]-=d*b[i]}}return b}
export function inverseQuad(q){let A=[],b=[];const uv=[[0,0],[1,0],[1,1],[0,1]];q.forEach(([x,y],i)=>{let[u,v]=uv[i];A.push([x,y,1,0,0,0,-u*x,-u*y]);b.push(u);A.push([0,0,0,x,y,1,-v*x,-v*y]);b.push(v)});let h=solve(A,b);return[h[0],h[3],h[6],h[1],h[4],h[7],h[2],h[5],1]}
export function project(g,img,q,{shadow=true,edge='#c0d5ca',blur=0,dof=0}={}){g.save();g.beginPath();q.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.closePath();if(shadow){g.shadowColor='#205b6120';g.shadowBlur=30;g.shadowOffsetY=5;g.fillStyle='#ffffff';g.fill()}g.shadowBlur=0;g.shadowOffsetY=0;gl.viewport(0,0,1920,1080);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,img);gl.uniform1f(gl.getUniformLocation(p,'dof'),dof);gl.uniformMatrix3fv(loc,false,new Float32Array(inverseQuad(q)));gl.drawArrays(gl.TRIANGLES,0,6);if(blur)g.filter=`blur(${blur}px)`;g.drawImage(surface,0,0);g.filter='none';g.strokeStyle=edge;g.lineWidth=1.7;g.stroke();g.restore()}
export const quadMix=(a,b,t)=>a.map((p,i)=>p.map((x,j)=>x+(b[i][j]-x)*t));
